antora:
  extensions:
    - '@springio/antora-extensions/partial-build-extension'
    - require: '@springio/antora-extensions/latest-version-extension'
    - require: '@springio/antora-extensions/inject-collector-cache-config-extension'
    - '@antora/collector-extension'
    - '@antora/atlas-extension'
    - require: '@springio/antora-extensions/root-component-extension'
      root_component_name: 'cloud-contract'
site:
  title: Spring Cloud Contract
  url: https://docs.spring.io/spring-cloud-contract/reference/
content:
  sources:
    - url: ./..
      branches: HEAD
      start_path: docs
      worktrees: true
asciidoc:
  attributes:
    page-stackoverflow-url: https://stackoverflow.com/tags/spring-cloud
    page-pagination: ''
    hide-uri-scheme: '@'
    tabs-sync-option: '@'
    chomp: 'all'
    plantuml-server-url: http://www.plantuml.com/plantuml
  extensions:
    - '@asciidoctor/tabs'
    - '@springio/asciidoctor-extensions' #TODO: Add plantuml rendering
  sourcemap: true
urls:
  latest_version_segment: ''
runtime:
  log:
    failure_level: error # at least until we figure out what's wrong in contract files
    format: pretty
ui:
  bundle:
    url: https://github.com/spring-io/antora-ui-spring/releases/download/v0.3.5/ui-bundle.zip
